// Portfolio content. See README.md for editing and adding projects.
export const portfolio = {
  name: 'Aryan Maurya',
  wordmark: 'ARYAN',
  title: 'Computer Engineering student',
  studyYear: 'Second year',
  college: 'Atharva College of Engineering',
  branch: 'Computer Engineering',
  heroLabel: 'Second-year Computer Engineering student at Atharva College of Engineering',
  headline: ['Engineer', 'in the', 'making.'],
  aboutHeading: 'A curious mind. A world to build.',
  about: "I'm Aryan Maurya, a second-year Computer Engineering student at Atharva College of Engineering, interested in web development and cybersecurity.",
  aboutDetail: 'I work with HTML, CSS and JavaScript, and I’m learning Python fundamentals through loops. This is a space for my learning, ideas and the projects I’ll share along the way.',
  facts: [
    { value: '02', label: 'Year of study' },
    { value: 'Web', label: 'Development' },
    { value: 'Python', label: 'Learning' },
    { value: 'Security', label: 'An interest' },
  ],
  interests: [
    { name: 'Web development', tag: 'BUILD', caption: 'Interfaces, interactions and the web' },
    { name: 'Cybersecurity', tag: 'EXPLORE', caption: 'Curious about how systems stay secure' },
    { name: 'Python', tag: 'LEARN', caption: 'Building foundations, one loop at a time' },
  ],
  skillsHeading: 'The tools. The practice. The next step.',
  skillsIntro: 'My foundation is in HTML, CSS and JavaScript. I’m learning Python and exploring an interest in cybersecurity. There’s always more to understand.',
  skills: [
    { name: 'HTML', tag: '01', description: 'The structure behind the pages I build.', status: 'Build with' },
    { name: 'CSS', tag: '02', description: 'Bringing layout, visual style and responsive pages together.', status: 'Build with' },
    { name: 'JavaScript', tag: '03', description: 'Adding logic and interaction to the web.', status: 'Build with' },
    { name: 'Python', tag: '04', description: 'Learning the fundamentals, currently through loops.', status: 'Learning' },
    { name: 'Cybersecurity', tag: '05', description: 'An area I’m interested in exploring as I learn more about computing.', status: 'Interested in' },
  ],
  projectsHeading: 'Selected work.',
  emptyProjectsHeading: 'Work, in progress.',
  emptyProjectsMessage: 'I’ll share my projects here as this portfolio grows. For now, find me on GitHub and follow along.',
  projects: [],
  contactMessage: 'Interested in web development, cybersecurity or learning together? Find me on LinkedIn, or explore my GitHub profile below.',
  links: {
    github: 'https://github.com/AryanMauryahere',
    linkedin: 'https://www.linkedin.com/in/aryan-maurya-96999734b',
    email: '',
    resume: '',
  },
};
